export const projectDescriptionsRussian: Record<string, string> = {
  "JobFinder": "Надёжные workflows: контроль версий состояния, transactional outbox, типизированные LLM-рецепты и обработка неизвестного результата внешней операции. Прошли 939 выбранных тестов, включая PostgreSQL и восстановление после остановки процесса.",
  "Slot Math Lab": "Интерпретаторы точных рациональных вероятностей и Monte Carlo, детерминированные RNG-потоки и React-редактор графов. Прошли 704 core-теста; исследовательский прототип, полный CI требует исправлений.",
  "Realtime Primitives": "Выделенная C# библиотека: circuit breakers, типизированные HTTP-сбои, повторное чтение сохранённого аудио и bounded flight recorder. 89 offline-тестов и публичный CI.",
  "AccessRoute for Revit": "BVH spatial search, Dijkstra, версионированное хранение и WPF/MVVM. 68 общих core/presentation тестов; индекс примерно в 11 раз быстрее полного обхода на синтетическом benchmark. Запуск внутри Revit не подтверждён.",
  "TGSlots": "Пять игр на TypeScript/PixiJS во главе с Nine Lives: каскады, сбор фишек и Monte Carlo tooling. X7 Club добавляет Go-сервер сессий и математический worker через RabbitMQ. Прошли 812 тестов платформы и 7 Go-тестов с race detector; проверены дубликаты запросов и расчёт бонусов через реальный API. Демонстрационные сессии хранятся в памяти.",
  ".NET Engineering Portfolio": "Этот monorepo: версионированный API, PostgreSQL/Redis, изолированные Testcontainers-тесты и двуязычный React-сайт. Прошли 56 backend- и 43 frontend-теста.",
  "ModelGuard for Revit": "Дополняющий BIM-инструмент: контракты параметров, ссылки на оборудование, транзакционное обновление марок и worksharing ownership. Core и тесты общие с AccessRoute; запуск внутри Revit не подтверждён.",
  "Trading Systems Lab": "C#/.NET и Go: protobuf/gRPC-контракты, состояния исполнения, неизменяемый PostgreSQL-аудит и независимый emergency watchdog. Прошли 151 .NET-тест и тесты Go; один benchmark пропущен. Live exchange behavior не проверялся.",
  "Signal Processing Lab": "Python async, типизированный LLM/media parsing, SQLite-кампании, dry-run исполнение и риск-правила. Прошли 340 offline-тестов. Очищенная исследовательская версия; live providers и screener не проверялись."
};
